language: objective-c
script:
	- xctool -workspace AirMenuKit.xcworkspace -scheme AirMenuKit -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
	- xctool test -workspace AirMenuKit.xcworkspace -scheme AirMenuKitTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
