language: objective-c
before_install:
 - cd Project
 - export LANG=en_US.UTF-8
 - gem update cocoapods --no-rdoc
 - brew update
 - brew upgrade xctool
 - pod install
 - cd ..	
script:
 - xctool -workspace Project/AirMenuKit.xcworkspace -scheme AirMenuKit -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
 - xctool test -workspace Project/AirMenuKit.xcworkspace -scheme AirMenuKitTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO