language: objective-c
script:
 - xctool -workspace Project/AirMenuKit.xcworkspace -scheme AirMenuKit -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
 - xctool test -workspace Project/AirMenuKit.xcworkspace -scheme AirMenuKitTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO